#Functions used:

#Functions for loading and saving localization data
def loc_load(locs_file):
    # import modules used
    import pandas as pd

    # Open localization file:
    locs_xy = pd.read_hdf(locs_file, key='locs')

    df_header = [x for x in locs_xy.columns]

    return locs_xy, df_header

def df_to_nprecarray(loc_xy_filt, df_header):
    # import modules used
    import numpy as np

    mydata = []
    for row in loc_xy_filt.values:
        mydata.append(row)

    mydata = np.array(mydata)

    header_l = []
    for i in range(len(df_header)):
        if i == 0:
            header_l.append((df_header[i], 'u4'))
        else:
            header_l.append((df_header[i], 'f4'))

    mydtype = np.dtype(header_l)

    myRecord = np.core.records.array(list(tuple(mydata.transpose())), dtype=mydtype)

    return myRecord

def export_hdf(file_name, data_rec_array):
    # import modules used
    import h5py

    with h5py.File(str(file_name[:-5]) + '_cropped.hdf5',
                   "w") as locs_file:
        locs_file.create_dataset("locs", data=data_rec_array)

def yaml_export(file_name):
    import yaml

    dict_file = [{'Generated by': 'Alignment script', 'bg': None, 'photons': None,
                  'lpx': None, 'lpy': None,
                  'ellipticity': None, 'frame': None, 'net_gradient': None, 'sx': None,
                  'sy': None, 'x': None, 'y': None}]


    with open(file_name[:-5] + '.yaml', "r") as stream:
        d = list(yaml.safe_load_all(stream))
        d.append(dict_file[0])

    with open(file_name[:-5] + '_cropped.yaml', "w") as stream:
        yaml.dump_all(d, stream, default_flow_style=False)

#Function for translating coordinates and removing non overlapping areas from datasets
def loc_crop(loc_df_l, pad, def_FOV):
    # import packages used
    import pandas as pd
    import math

    #Determine border coordinates for data sets
    loc_x_lim = [[],[]]
    loc_y_lim = [[],[]]
    for i in range(len(loc_df_l)):
        loc_x_lim[0].append(loc_df_l[i]['x'].min())
        loc_x_lim[1].append(loc_df_l[i]['x'].max())
        loc_y_lim[0].append(loc_df_l[i]['y'].min())
        loc_y_lim[1].append(loc_df_l[i]['y'].max())

    border_coor = [[math.ceil(max(loc_x_lim[0])-pad), math.floor(min(loc_x_lim[1])+pad)],[math.ceil(max(loc_y_lim[0])-pad), math.floor(min(loc_y_lim[1])+pad)]]
    seg_img_size = [border_coor[0][1]-border_coor[0][0],border_coor[1][1]-border_coor[1][0]]
    cent_coor = [int((border_coor[0][0]+border_coor[0][1])/2),int((border_coor[1][0]+border_coor[1][1])/2)]
    final_FOV_size= seg_img_size

    #Apply pre-defined FOV size if specified and if smaller then determined FOV size
    if def_FOV[0] == True:
        FOV_size = [def_FOV[1],def_FOV[2]]
        if seg_img_size[0] > FOV_size[0] and seg_img_size[1] > FOV_size[1]:
            border_coor = [[int(cent_coor[0]-int(FOV_size[0]/2)-pad),int(cent_coor[0]+int(FOV_size[0]/2)+pad)],[int(cent_coor[1]-int(FOV_size[1]/2)-pad),int(cent_coor[1]+int(FOV_size[1]/2)+pad)]]
            final_FOV_size = FOV_size

    #
    for i in range(len(loc_df_l)):
        loc_df_l[i] = loc_df_l[i].loc[(border_coor[0][0] < loc_df_l[i]['x']) & (border_coor[0][1] > loc_df_l[i]['x']) & (border_coor[1][0] < loc_df_l[i]['y'])& (border_coor[1][1] > loc_df_l[i]['y'])]

    #
    for i in range(len(loc_df_l)):
        loc_df_l[i]['x'] -= border_coor[0][0]
        loc_df_l[i]['y'] -= border_coor[1][0]

    return loc_df_l, border_coor, final_FOV_size

def PAINT_crop_main_gui():
    # import modules used
    import PySimpleGUI as sg

    # Input information needed for processing

    left_col = [
        [sg.Frame('Data information:',
                  [[sg.Text('Number of channels in PAINT data:', size=(36, 1)),
                    sg.InputText(key='PAINT_channel_n', size=(8, 1))],
                   [sg.Checkbox('Predefined FOV size', size=(30, 1), key='chk_def_FOV')]
                   ])],
        [sg.Button('Select localization files'), sg.Button('Cancel')]
    ]
    right_col = [
        [sg.Frame('Output:', [[sg.Multiline("", size=(50, 10), key='OUTPUT')]])]
    ]

    layout = [[sg.Column(left_col, element_justification='c'),
               sg.Column(right_col, element_justification='c', vertical_alignment="top")]]
    window_crop_main = sg.Window('PAINT data cropping main', layout, resizable=True)

    #
    while True:
        event, values = window_crop_main.read()
        if event == sg.WIN_CLOSED or event == 'Cancel':
            window_crop_main.close()
            break

        if event == 'Select localization files':
            try:
                PAINT_channel_n = int(values['PAINT_channel_n'])
                def_FOV = values['chk_def_FOV']
                PAINT_crop_gui(channel_n=PAINT_channel_n, def_FOV=def_FOV)

            except ValueError:
                sg.Popup('Could not proceed with rendering. Check if all parameters are provided correctly.')


def PAINT_crop_gui(channel_n, def_FOV):
    # import modules used
    import pandas as pd
    import PySimpleGUI as sg
    import csv
    from tqdm import tqdm
    import glob


    # Input information needed for processing
    #
    left_col = []

    for i in range(channel_n):
        left_col.append([sg.Frame('Channel ' + str(i) + ' information:',
                                  [[sg.Text('PAINT localization file for channel:'),
                                    sg.In(size=(50, 1), enable_events=True, key='file-ch-' + str(i)),
                                    sg.FileBrowse()],
                                   [sg.Text('Name of imager sequence used for channel:', size=(25, 1)),
                                    sg.InputText(key='PAINT_img_name-ch-' + str(i), size=(8, 1))]
                                   ])])

    data_proc_info = [[sg.Text('Folder to save data to:'),
                                    sg.In(size=(50, 1), enable_events=True, key='export_folder'),
                                    sg.FolderBrowse()],
                      [sg.Text('Padding size (pixel):', size=(25, 1)),
                       sg.InputText(default_text='0',key='pad', size=(8, 1))]
                      ]
    if def_FOV == True:
        data_proc_info.append([sg.Text('FOV size:', size=(25, 1)),
                                    sg.InputText(key='FOV_x', size=(8, 1)),
                                    sg.InputText(key='FOV_y', size=(8, 1))])

    left_col.append([sg.Frame('Information for data processing:',
                                  data_proc_info
                                  )])
    left_col.append([sg.Button('Crop data'), sg.Button('Cancel')])

    right_col = [
        [sg.Frame('Output:', [[sg.Multiline("", size=(50, 10), key='OUTPUT')]])],
        [sg.Frame('Progress:', [[sg.Multiline("", size=(50, 1), key='OUTPUT2')]])]
    ]

    layout = [[sg.Column(left_col, element_justification='c'),
               sg.Column(right_col, element_justification='c', vertical_alignment="top")]]
    window_data_crop = sg.Window('PAINT data cropping', layout, resizable=True)

    #
    loc_files = []
    click_memory_loc = []

    for i in range(channel_n):
        click_memory_loc.append(0)


    while True:
        event, values = window_data_crop.read()
        if event == sg.WIN_CLOSED or event == 'Cancel':
            window_data_crop.close()
            break

        #Create lists to store data for processing
        channel_names = []
        data_set_locs = []
        data_set_headers = []

        if event == 'export_folder':
            exp_folder = values['export_folder']

        for j in range(channel_n):

            if event == 'file-ch-' + str(j):

                click_memory_loc[j] = click_memory_loc[j] + 1
                if click_memory_loc[j] < 2:
                    loc_files.append(values['file-ch-' + str(j)])
                else:
                    loc_files[j] = values['file-ch-' + str(j)]


        if event == 'Crop data':
            window_data_crop['OUTPUT'].update(
                value='')
            window_data_crop.refresh()

            if len(exp_folder) == 0 :
                sg.Popup('Folder for exporting data not specified.')
                break

            else:
                if '' in loc_files:
                    sg.Popup('Localization file(s) not specified.')
                    break

                else:
                    for loc_file in loc_files:
                        if not glob.glob(loc_file[:-5] + '.yaml'):
                            sg.Popup('No yaml file found in the specified folder.')

                    for h in range(len(loc_files)):
                        channel_names.append(str(values['PAINT_img_name-ch-' + str(h)]))

                    if '' in channel_names:
                        sg.Popup('Channel name(s) not provided.')
                        break

                    else:
                        pad = int(values['pad'])
                        if def_FOV == True:
                            if len(values['FOV_x'])!=0 or len(values['FOV_y'])!=0 :
                                FOV_l = [def_FOV, int(values['FOV_x']), int(values['FOV_y'])]

                            else:
                                sg.Popup('FOV size not provided.')
                                break
                        else:
                            FOV_l = [def_FOV]

                        with open(exp_folder + '/Crop_info.csv', 'w', newline='') as csvfile:

                            spamwriter = csv.writer(csvfile, delimiter=',', quotechar='"',
                                                    quoting=csv.QUOTE_MINIMAL)
                            spamwriter.writerow(['Data path', 'Channel name'])
                            for k in range(channel_n):
                                data_path = loc_files[k]
                                channel_name = channel_names[k]
                                spamwriter.writerow([data_path, channel_name])


                        for k in range(channel_n):
                            loc_file = loc_files[k]
                            loc_file_ch_name = channel_names[k]


                            window_data_crop['OUTPUT'].update(value='Localization file loaded:' + '\n', append=True)
                            window_data_crop.refresh()
                            window_data_crop['OUTPUT'].update(value=loc_file + '\n', append=True)
                            window_data_crop.refresh()
                            window_data_crop['OUTPUT'].update(value=loc_file_ch_name + '\n', append=True)
                            window_data_crop.refresh()

                            # Import loc file and transform it into a np array
                            locs_df, df_header = loc_load(locs_file=loc_file)
                            data_set_locs.append(locs_df)
                            data_set_headers.append(df_header)

                    #Generating cropped datasets by removing non-overlapping segments from datasets
                    window_data_crop['OUTPUT'].update(value='Generating cropped datasets'+ '\n', append=True)
                    window_data_crop.refresh()
                    crop_loc_df_l, border_coor, final_FOV_size = loc_crop(loc_df_l=data_set_locs, pad=pad, def_FOV=FOV_l)

                    #Export crop coordinates and final image size
                    window_data_crop['OUTPUT'].update(value='Exporting cropped datasets'+ '\n', append=True)
                    window_data_crop.refresh()
                    with open(exp_folder + '/Crop_info.csv', 'w', newline='') as csvfile:
                        spamwriter = csv.writer(csvfile, delimiter=',', quotechar='"',
                                               quoting=csv.QUOTE_MINIMAL)
                        spamwriter.writerow(['Crop border coordinates'])
                        spamwriter.writerow(['x_min','x_max','y_min','y_max'])
                        spamwriter.writerow([border_coor[0][0],border_coor[0][1],border_coor[1][0],border_coor[1][1]])
                        spamwriter.writerow(['Final image size'])
                        spamwriter.writerow(final_FOV_size)

                    #Export cropped localizations datasets

                    for h in range(len(crop_loc_df_l)):
                        crop_loc_df = crop_loc_df_l[h]
                        loc_df_header = data_set_headers[h]
                        file_name = loc_files[h]

                        myRecord = df_to_nprecarray(loc_xy_filt=crop_loc_df, df_header=loc_df_header)
                        export_hdf(file_name=file_name, data_rec_array=myRecord)
                        yaml_export(file_name=file_name)

                    window_data_crop['OUTPUT'].update(value='Finished processing'+ '\n', append=True)
                    window_data_crop.refresh()
